name: sora_flutter
description: "Cross-platform streaming app with JavaScript service support"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  
  # Networking & HTTP
  dio: ^5.4.3+1
  http: ^1.2.2
  
  # JavaScript Engine
  flutter_js: ^0.8.0
  
  # Video Player
  video_player: ^2.8.6
  chewie: ^1.8.3
  
  # Images & Caching
  cached_network_image: ^3.3.1
  palette_generator: ^0.3.3+3
  
  # Storage & Database
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  
  # JSON & Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # Utils
  uuid: ^4.4.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.13

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/js/
